export const currencyInfo = {
  // Major Global Currencies
  USD: { flag: '🇺🇸', name: 'US Dollar' },
  EUR: { flag: '🇪🇺', name: 'Euro' },
  JPY: { flag: '🇯🇵', name: 'Japanese Yen' },
  GBP: { flag: '🇬🇧', name: 'British Pound' },
  AUD: { flag: '🇦🇺', name: 'Australian Dollar' },
  CAD: { flag: '🇨🇦', name: 'Canadian Dollar' },
  CHF: { flag: '🇨🇭', name: 'Swiss Franc' },
  CNY: { flag: '🇨🇳', name: 'Chinese Yuan' },
  HKD: { flag: '🇭🇰', name: 'Hong Kong Dollar' },
  NZD: { flag: '🇳🇿', name: 'New Zealand Dollar' },
  SEK: { flag: '🇸🇪', name: 'Swedish Krona' },
  KRW: { flag: '🇰🇷', name: 'South Korean Won' },
  SGD: { flag: '🇸🇬', name: 'Singapore Dollar' },
  NOK: { flag: '🇳🇴', name: 'Norwegian Krone' },
  MXN: { flag: '🇲🇽', name: 'Mexican Peso' },
  INR: { flag: '🇮🇳', name: 'Indian Rupee' },
  RUB: { flag: '🇷🇺', name: 'Russian Ruble' },
  ZAR: { flag: '🇿🇦', name: 'South African Rand' },
  TRY: { flag: '🇹🇷', name: 'Turkish Lira' },
  BRL: { flag: '🇧🇷', name: 'Brazilian Real' },

  // Arab World Currencies
  EGP: { flag: '🇪🇬', name: 'Egyptian Pound' },
  SAR: { flag: '🇸🇦', name: 'Saudi Riyal' },
  AED: { flag: '🇦🇪', name: 'UAE Dirham' },
  KWD: { flag: '🇰🇼', name: 'Kuwaiti Dinar' },
  QAR: { flag: '🇶🇦', name: 'Qatari Riyal' },
  OMR: { flag: '🇴🇲', name: 'Omani Rial' },
  BHD: { flag: '🇧🇭', name: 'Bahraini Dinar' },
  JOD: { flag: '🇯🇴', name: 'Jordanian Dinar' },
  LBP: { flag: '🇱🇧', name: 'Lebanese Pound' },
  MAD: { flag: '🇲🇦', name: 'Moroccan Dirham' },
  IQD: { flag: '🇮🇶', name: 'Iraqi Dinar' },
  TND: { flag: '🇹🇳', name: 'Tunisian Dinar' },
  DZD: { flag: '🇩🇿', name: 'Algerian Dinar' },
  LYD: { flag: '🇱🇾', name: 'Libyan Dinar' },
  SYP: { flag: '🇸🇾', name: 'Syrian Pound' },
  YER: { flag: '🇾🇪', name: 'Yemeni Rial' },
  SDG: { flag: '🇸🇩', name: 'Sudanese Pound' },
  SOS: { flag: '🇸🇴', name: 'Somali Shilling' },
  DJF: { flag: '🇩🇯', name: 'Djiboutian Franc' },
  KMF: { flag: '🇰🇲', name: 'Comorian Franc' },
  MRU: { flag: '🇲🇷', name: 'Mauritanian Ouguiya' },

  // Other Global Currencies (Alphabetical)
  AFN: { flag: '🇦🇫', name: 'Afghan Afghani' },
  ALL: { flag: '🇦🇱', name: 'Albanian Lek' },
  AMD: { flag: '🇦🇲', name: 'Armenian Dram' },
  ANG: { flag: '🇳🇱', name: 'Neth. Antillean Guilder' },
  AOA: { flag: '🇦🇴', name: 'Angolan Kwanza' },
  ARS: { flag: '🇦🇷', name: 'Argentine Peso' },
  AWG: { flag: '🇦🇼', name: 'Aruban Florin' },
  AZN: { flag: '🇦🇿', name: 'Azerbaijani Manat' },
  BAM: { flag: '🇧🇦', name: 'Bosnia-Herzegovina Mark' },
  BBD: { flag: '🇧🇧', name: 'Barbadian Dollar' },
  BDT: { flag: '🇧🇩', name: 'Bangladeshi Taka' },
  BGN: { flag: '🇧🇬', name: 'Bulgarian Lev' },
  BIF: { flag: '🇧🇮', name: 'Burundian Franc' },
  BMD: { flag: '🇧🇲', name: 'Bermudian Dollar' },
  BND: { flag: '🇧🇳', name: 'Brunei Dollar' },
  BOB: { flag: '🇧🇴', name: 'Bolivian Boliviano' },
  BSD: { flag: '🇧🇸', name: 'Bahamian Dollar' },
  BTN: { flag: '🇧🇹', name: 'Bhutanese Ngultrum' },
  BWP: { flag: '🇧🇼', name: 'Botswanan Pula' },
  BYN: { flag: '🇧🇾', name: 'Belarusian Ruble' },
  BZD: { flag: '🇧🇿', name: 'Belize Dollar' },
  CDF: { flag: '🇨🇩', name: 'Congolese Franc' },
  CLP: { flag: '🇨🇱', name: 'Chilean Peso' },
  COP: { flag: '🇨🇴', name: 'Colombian Peso' },
  CRC: { flag: '🇨🇷', name: 'Costa Rican Colón' },
  CUP: { flag: '🇨🇺', name: 'Cuban Peso' },
  CVE: { flag: '🇨🇻', name: 'Cape Verdean Escudo' },
  CZK: { flag: '🇨🇿', name: 'Czech Koruna' },
  DKK: { flag: '🇩🇰', name: 'Danish Krone' },
  DOP: { flag: '🇩🇴', name: 'Dominican Peso' },
  ERN: { flag: '🇪🇷', name: 'Eritrean Nakfa' },
  ETB: { flag: '🇪🇹', name: 'Ethiopian Birr' },
  FJD: { flag: '🇫🇯', name: 'Fijian Dollar' },
  FKP: { flag: '🇫🇰', name: 'Falkland Islands Pound' },
  GEL: { flag: '🇬🇪', name: 'Georgian Lari' },
  GGP: { flag: '🇬🇬', name: 'Guernsey Pound' },
  GHS: { flag: '🇬🇭', name: 'Ghanaian Cedi' },
  GIP: { flag: '🇬🇮', name: 'Gibraltar Pound' },
  GMD: { flag: '🇬🇲', name: 'Gambian Dalasi' },
  GNF: { flag: '🇬🇳', name: 'Guinean Franc' },
  GTQ: { flag: '🇬🇹', name: 'Guatemalan Quetzal' },
  GYD: { flag: '🇬🇾', name: 'Guyanese Dollar' },
  HNL: { flag: '🇭🇳', name: 'Honduran Lempira' },
  HRK: { flag: '🇭🇷', name: 'Croatian Kuna' },
  HTG: { flag: '🇭🇹', name: 'Haitian Gourde' },
  HUF: { flag: '🇭🇺', name: 'Hungarian Forint' },
  IDR: { flag: '🇮🇩', name: 'Indonesian Rupiah' },
  ILS: { flag: '🇮🇱', name: 'Israeli New Shekel' },
  IMP: { flag: '🇮🇲', name: 'Isle of Man Pound' },
  ISK: { flag: '🇮🇸', name: 'Icelandic Króna' },
  JEP: { flag: '🇯🇪', name: 'Jersey Pound' },
  JMD: { flag: '🇯🇲', name: 'Jamaican Dollar' },
  KES: { flag: '🇰🇪', name: 'Kenyan Shilling' },
  KGS: { flag: '🇰🇬', name: 'Kyrgystani Som' },
  KHR: { flag: '🇰🇭', name: 'Cambodian Riel' },
  KZT: { flag: '🇰🇿', name: 'Kazakhstani Tenge' },
  LAK: { flag: '🇱🇦', name: 'Laotian Kip' },
  LKR: { flag: '🇱🇰', name: 'Sri Lankan Rupee' },
  LRD: { flag: '🇱🇷', name: 'Liberian Dollar' },
  LSL: { flag: '🇱🇸', name: 'Lesotho Loti' },
  MDL: { flag: '🇲🇩', name: 'Moldovan Leu' },
  MGA: { flag: '🇲🇬', name: 'Madagascan Ariary' },
  MKD: { flag: '🇲🇰', name: 'Macedonian Denar' },
  MMK: { flag: '🇲🇲', name: 'Myanmar Kyat' },
  MNT: { flag: '🇲🇳', name: 'Mongolian Tugrik' },
  MOP: { flag: '🇲🇴', name: 'Macanese Pataca' },
  MUR: { flag: '🇲🇺', name: 'Mauritian Rupee' },
  MVR: { flag: '🇲🇻', name: 'Maldivian Rufiyaa' },
  MWK: { flag: '🇲🇼', name: 'Malawian Kwacha' },
  MYR: { flag: '🇲🇾', name: 'Malaysian Ringgit' },
  MZN: { flag: '🇲🇿', name: 'Mozambican Metical' },
  NAD: { flag: '🇳🇦', name: 'Namibian Dollar' },
  NGN: { flag: '🇳🇬', name: 'Nigerian Naira' },
  NIO: { flag: '🇳🇮', name: 'Nicaraguan Córdoba' },
  NPR: { flag: '🇳🇵', name: 'Nepalese Rupee' },
  PAB: { flag: '🇵🇦', name: 'Panamanian Balboa' },
  PEN: { flag: '🇵🇪', name: 'Peruvian Sol' },
  PGK: { flag: '🇵🇬', name: 'Papua New Guinean Kina' },
  PHP: { flag: '🇵🇭', name: 'Philippine Peso' },
  PKR: { flag: '🇵🇰', name: 'Pakistani Rupee' },
  PLN: { flag: '🇵🇱', name: 'Polish Zloty' },
  PYG: { flag: '🇵🇾', name: 'Paraguayan Guarani' },
  RON: { flag: '🇷🇴', name: 'Romanian Leu' },
  RSD: { flag: '🇷🇸', name: 'Serbian Dinar' },
  RWF: { flag: '🇷🇼', name: 'Rwandan Franc' },
  SBD: { flag: '🇸🇧', name: 'Solomon Islands Dollar' },
  SCR: { flag: '🇸🇨', name: 'Seychellois Rupee' },
  SHP: { flag: '🇸🇭', name: 'Saint Helena Pound' },
  SLL: { flag: '🇸🇱', name: 'Sierra Leonean Leone' },
  SRD: { flag: '🇸🇷', name: 'Surinamese Dollar' },
  SSP: { flag: '🇸🇸', name: 'South Sudanese Pound' },
  STN: { flag: '🇸🇹', name: 'São Tomé and Príncipe Dobra' },
  SZL: { flag: '🇸🇿', name: 'Swazi Lilangeni' },
  THB: { flag: '🇹🇭', name: 'Thai Baht' },
  TJS: { flag: '🇹🇯', name: 'Tajikistani Somoni' },
  TMT: { flag: '🇹🇲', name: 'Turkmenistani Manat' },
  TOP: { flag: '🇹🇴', name: 'Tongan Paʻanga' },
  TTD: { flag: '🇹🇹', name: 'Trinidad and Tobago Dollar' },
  TWD: { flag: '🇹🇼', name: 'New Taiwan Dollar' },
  TZS: { flag: '🇹🇿', name: 'Tanzanian Shilling' },
  UAH: { flag: '🇺🇦', name: 'Ukrainian Hryvnia' },
  UGX: { flag: '🇺🇬', name: 'Ugandan Shilling' },
  UYU: { flag: '🇺🇾', name: 'Uruguayan Peso' },
  UZS: { flag: '🇺🇿', name: 'Uzbekistani Som' },
  VES: { flag: '🇻🇪', name: 'Venezuelan Bolívar' },
  VND: { flag: '🇻🇳', name: 'Vietnamese Dong' },
  VUV: { flag: '🇻🇺', name: 'Vanuatu Vatu' },
  WST: { flag: '🇼🇸', name: 'Samoan Tala' },
  XAF: { flag: '🇨🇲', name: 'Central African CFA Franc' },
  XCD: { flag: '🇰🇳', name: 'East Caribbean Dollar' },
  XOF: { flag: '🇸🇳', name: 'West African CFA Franc' },
  XPF: { flag: '🇵🇫', name: 'CFP Franc' },
  ZMW: { flag: '🇿🇲', name: 'Zambian Kwacha' },
  ZWL: { flag: '🇿🇼', name: 'Zimbabwean Dollar' },
};

export const getSortedCurrencies = (favorites = []) => {
  const allKeys = Object.keys(currencyInfo);
  
  return allKeys.sort((a, b) => {
    const indexA = favorites.indexOf(a);
    const indexB = favorites.indexOf(b);

    if (indexA !== -1 && indexB !== -1) return indexA - indexB;
    if (indexA !== -1) return -1;
    if (indexB !== -1) return 1;

    return a.localeCompare(b);
  });
};
